# Generated by Django 4.1 on 2024-07-10 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 16, 25, 52, 866848, tzinfo=datetime.timezone.utc)),
        ),
    ]
